-- AlterTable
ALTER TABLE "TourRegistration" ADD COLUMN     "dueAmount" DOUBLE PRECISION NOT NULL DEFAULT 4500,
ADD COLUMN     "paidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 4500;
